Add mutually recursive definition support for AE
Gbury/dolmen pull request #129
Opened 2023-02-09 15:17 UTC by Halbaroth

This PR adds the support for mutually recursive functions in the native language of AE.

2023-02-09 15:32 UTC, Gbury requested changes

2023-02-09 16:01 UTC, Halbaroth commented on src/interface/stmt.ml
> +  val mut_fun_def_rec : ?loc:location -> t list -> t
Right! I though `defs` was for type definitions only.

2023-02-10 08:38 UTC, Halbaroth commented
I added also support for mutually recursive predicates. Even if the keyword `predicate` is now a alias for function with return type `Prop`, it is nicer to write `predicate .... and predicate ...`. Notice, we cannot mix the two constructions.

2023-02-10 15:08 UTC, Gbury approved these changes

2023-02-10 15:38 UTC, Halbaroth commented
@hra687261 told me `function` and `predicate` can be used at the same time in its implementation of mutually recursive definition. Thus, I have to modify this PR to have the same feature.

2023-02-10 15:41 UTC, Gbury commented
@Halbaroth I commited and pushed to this PR the changes required to support a mix of `predicate` and `function` in the same mutually recursive group, so it's okay, you don't have to do it.

2023-02-10 16:05 UTC, merged